/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RandomRouteImport } from './routes/random'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WordsNewRouteImport } from './routes/words.new'
import { Route as WordsIdRouteImport } from './routes/words.$id'
import { Route as WordsIdEditRouteImport } from './routes/words_.$id.edit'
import { Route as ApiPublicVocabIndexRouteImport } from './routes/api.public.vocab.index'
import { Route as ApiPublicVocabRandomRouteImport } from './routes/api.public.vocab.random'
import { Route as ApiPublicVocabIdRouteImport } from './routes/api.public.vocab.$id'

const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsNewRoute = WordsNewRouteImport.update({
  id: '/words/new',
  path: '/words/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIdRoute = WordsIdRouteImport.update({
  id: '/words/$id',
  path: '/words/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIdEditRoute = WordsIdEditRouteImport.update({
  id: '/words_/$id/edit',
  path: '/words/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVocabIndexRoute = ApiPublicVocabIndexRouteImport.update({
  id: '/api/public/vocab/',
  path: '/api/public/vocab/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVocabRandomRoute = ApiPublicVocabRandomRouteImport.update({
  id: '/api/public/vocab/random',
  path: '/api/public/vocab/random',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVocabIdRoute = ApiPublicVocabIdRouteImport.update({
  id: '/api/public/vocab/$id',
  path: '/api/public/vocab/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/random': typeof RandomRoute
  '/words/$id': typeof WordsIdRoute
  '/words/new': typeof WordsNewRoute
  '/words/$id/edit': typeof WordsIdEditRoute
  '/api/public/vocab/$id': typeof ApiPublicVocabIdRoute
  '/api/public/vocab/random': typeof ApiPublicVocabRandomRoute
  '/api/public/vocab/': typeof ApiPublicVocabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/random': typeof RandomRoute
  '/words/$id': typeof WordsIdRoute
  '/words/new': typeof WordsNewRoute
  '/words/$id/edit': typeof WordsIdEditRoute
  '/api/public/vocab/$id': typeof ApiPublicVocabIdRoute
  '/api/public/vocab/random': typeof ApiPublicVocabRandomRoute
  '/api/public/vocab': typeof ApiPublicVocabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-docs': typeof ApiDocsRoute
  '/random': typeof RandomRoute
  '/words/$id': typeof WordsIdRoute
  '/words/new': typeof WordsNewRoute
  '/words_/$id/edit': typeof WordsIdEditRoute
  '/api/public/vocab/$id': typeof ApiPublicVocabIdRoute
  '/api/public/vocab/random': typeof ApiPublicVocabRandomRoute
  '/api/public/vocab/': typeof ApiPublicVocabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-docs'
    | '/random'
    | '/words/$id'
    | '/words/new'
    | '/words/$id/edit'
    | '/api/public/vocab/$id'
    | '/api/public/vocab/random'
    | '/api/public/vocab/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-docs'
    | '/random'
    | '/words/$id'
    | '/words/new'
    | '/words/$id/edit'
    | '/api/public/vocab/$id'
    | '/api/public/vocab/random'
    | '/api/public/vocab'
  id:
    | '__root__'
    | '/'
    | '/api-docs'
    | '/random'
    | '/words/$id'
    | '/words/new'
    | '/words_/$id/edit'
    | '/api/public/vocab/$id'
    | '/api/public/vocab/random'
    | '/api/public/vocab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDocsRoute: typeof ApiDocsRoute
  RandomRoute: typeof RandomRoute
  WordsIdRoute: typeof WordsIdRoute
  WordsNewRoute: typeof WordsNewRoute
  WordsIdEditRoute: typeof WordsIdEditRoute
  ApiPublicVocabIdRoute: typeof ApiPublicVocabIdRoute
  ApiPublicVocabRandomRoute: typeof ApiPublicVocabRandomRoute
  ApiPublicVocabIndexRoute: typeof ApiPublicVocabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/new': {
      id: '/words/new'
      path: '/words/new'
      fullPath: '/words/new'
      preLoaderRoute: typeof WordsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/$id': {
      id: '/words/$id'
      path: '/words/$id'
      fullPath: '/words/$id'
      preLoaderRoute: typeof WordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words_/$id/edit': {
      id: '/words_/$id/edit'
      path: '/words/$id/edit'
      fullPath: '/words/$id/edit'
      preLoaderRoute: typeof WordsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vocab/': {
      id: '/api/public/vocab/'
      path: '/api/public/vocab'
      fullPath: '/api/public/vocab/'
      preLoaderRoute: typeof ApiPublicVocabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vocab/random': {
      id: '/api/public/vocab/random'
      path: '/api/public/vocab/random'
      fullPath: '/api/public/vocab/random'
      preLoaderRoute: typeof ApiPublicVocabRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vocab/$id': {
      id: '/api/public/vocab/$id'
      path: '/api/public/vocab/$id'
      fullPath: '/api/public/vocab/$id'
      preLoaderRoute: typeof ApiPublicVocabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDocsRoute: ApiDocsRoute,
  RandomRoute: RandomRoute,
  WordsIdRoute: WordsIdRoute,
  WordsNewRoute: WordsNewRoute,
  WordsIdEditRoute: WordsIdEditRoute,
  ApiPublicVocabIdRoute: ApiPublicVocabIdRoute,
  ApiPublicVocabRandomRoute: ApiPublicVocabRandomRoute,
  ApiPublicVocabIndexRoute: ApiPublicVocabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
